src/Entity/Enfant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EnfantRepository")
 * @UniqueEntity(fields={"nom","prenom","dateNaiss"}, message="Cet enfant est déjà enregistré !")
 */
class Enfant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom de l'enfant n'est pas renseigné !")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le prénom de l'enfant n'est pas renseigné !")
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="Le date de naissance de l'enfant n'est pas renseignée !")
     */
    private $dateNaiss;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $remarque;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="L'adresse de l'enfant n'est pas renseignée !")
     */
    private $adresse_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse_2;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="La ville où habite l'enfant n'est pas renseignée !")
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank(message="Le code postal n'est pas renseigné !")
     */
    private $code_postal;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etablissement", inversedBy="enfants", cascade={"persist"})
     */
    private $etablissement;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Centre", inversedBy="enfants")
     * @Assert\NotBlank(message="Le centre où doit être inscrit l'enfant n'est pas renseigné !")
     */
    private $centre;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Sejour", inversedBy="enfants")
     */
    private $sejour;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ResponsableLegal", inversedBy="enfants", cascade={"persist"})
     */
    private $responsable_legal;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CorrespondantAdministratif", inversedBy="enfants", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $correspondant_administratif;

    /**
     * @Assert\Valid
     */
    private $new_etablissement;

    /**
     * @Assert\Valid
     */
    private $new_correspondantAdministratif;

    /**
     * @Assert\Valid
     */
    private $new_responsableLegal;

    /**
     * @Assert\IsFalse(message="Un même responsable ne peut avoir deux rôles à la fois !")
     */
    public function isCorrespAsSameAsResp(){
        return $this->getResponsableLegal() === $this->getCorrespondantAdministratif()->getResponsableLegal();
    }

    public function __construct()
    {
        $this->sejour = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaiss(): ?\DateTimeInterface
    {
        return $this->dateNaiss;
    }

    public function setDateNaiss(\DateTimeInterface $dateNaiss): self
    {
        $this->dateNaiss = $dateNaiss;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(?string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    public function getAdresse1(): ?string
    {
        return $this->adresse_1;
    }

    public function setAdresse1(string $adresse_1): self
    {
        $this->adresse_1 = $adresse_1;

        return $this;
    }

    public function getAdresse2(): ?string
    {
        return $this->adresse_2;
    }

    public function setAdresse2(?string $adresse_2): self
    {
        $this->adresse_2 = $adresse_2;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getEtablissement(): ?Etablissement
    {
        return $this->etablissement;
    }

    public function setEtablissement(?Etablissement $etablissement): self
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    public function getCentre(): ?Centre
    {
        return $this->centre;
    }

    public function setCentre(?Centre $centre): self
    {
        $this->centre = $centre;

        return $this;
    }

    /**
     * @return Collection|Sejour[]
     */
    public function getSejour(): Collection
    {
        return $this->sejour;
    }

    public function addSejour(Sejour $sejour): self
    {
        if (!$this->sejour->contains($sejour)) {
            $this->sejour[] = $sejour;
        }

        return $this;
    }

    public function removeSejour(Sejour $sejour): self
    {
        if ($this->sejour->contains($sejour)) {
            $this->sejour->removeElement($sejour);
        }

        return $this;
    }

    public function getResponsableLegal(): ?ResponsableLegal
    {
        return $this->responsable_legal;
    }

    public function setResponsableLegal(?ResponsableLegal $responsable_legal): self
    {
        $this->responsable_legal = $responsable_legal;

        return $this;
    }

    public function getCorrespondantAdministratif(): ?CorrespondantAdministratif
    {
        return $this->correspondant_administratif;
    }

    public function setCorrespondantAdministratif(?CorrespondantAdministratif $correspondant_administratif): self
    {
        $this->correspondant_administratif = $correspondant_administratif;

        return $this;
    }

    public function getNewEtablissement(): ?Etablissement
    {
        return $this->new_etablissement;
    }

    public function setNewEtablissement(?Etablissement $new_etablissement): self
    {
        $this->new_etablissement = $new_etablissement;

        return $this;
    }

    public function getNewCorrespondantAdministratif(): ?CorrespondantAdministratif
    {
        return $this->new_correspondantAdministratif;
    }

    public function setNewCorrespondantAdministratif(?CorrespondantAdministratif $new_correspondantAdministratif): self
    {
        $this->new_correspondantAdministratif = $new_correspondantAdministratif;

        return $this;
    }

    public function getNewResponsableLegal(): ?ResponsableLegal
    {
        return $this->new_responsableLegal;
    }

    public function setNewResponsableLegal(?ResponsableLegal $new_responsableLegal): self
    {
        $this->new_responsableLegal = $new_responsableLegal;

        return $this;
    }
}

src/Controller/EnfantController.php
<?php

namespace App\Controller;

use App\Entity\Enfant;
use App\Form\EnfantType;
use App\Repository\EnfantRepository;
use Symfony\Component\Form\FormTypeInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\CorrespondantAdministratif;
use App\Entity\ResponsableLegal;
use App\Entity\Etablissement;

use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @Route("/gestionEnfants")
 */
class EnfantController extends AbstractController
{
    /**
     * @Route("/", name="enfant_index", methods={"GET"})
     */
    public function index(EnfantRepository $enfantRepository): Response
    {
        return $this->render('enfant/index.html.twig', [
            'enfants' => $enfantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/creation", name="enfant_creation", methods={"GET","POST"})
     */
    public function new(Request $request, ValidatorInterface $validator): Response
    {
        $enfant = new Enfant();

        $form = $this->createForm(EnfantType::class, $enfant);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if($form->isValid()){
                $manager = $this->getDoctrine()->getManager();

                $donnes_enfant = $form->getData();
                //Récupération des données formulaires de saisie d'un éventuel nouvel établissement/correspondant administratif/responsable légal
                $donnees_newEtablissement = $donnes_enfant->getNewEtablissement();
                $donnees_newRespLegal = $donnes_enfant->getNewResponsableLegal();
                $donnees_newCorrespAdmin = $donnes_enfant->getNewCorrespondantAdministratif();

                if($donnees_newEtablissement != null){
                    $this->enregistrerNouvelEtablissement($donnees_newEtablissement, $enfant);
                }

                //Enregistrement de l'éventuel nouveau établissement
                if($donnees_newRespLegal != null){
                    $this->enregisterNouveauResp($donnees_newRespLegal, $enfant);
                }

                //Enregistrement de l'éventuel correspondant administratif
                if($donnees_newCorrespAdmin != null){
                    $this->enregistrerNouveauCorresp($donnees_newCorrespAdmin, $enfant);
                }

                $manager->persist($enfant);
                $manager->flush();

                $this->addFlash('success', $donnes_enfant->getPrenom()." ".$donnes_enfant->getNom()." a été inscrit(e) avec succès !");

                return $this->redirectToRoute('enfant_index');
            }else{
                $errors = $validator->validate($form->getData());

                foreach ($errors as $error) {
                    $this->addFlash('error', $error->getMessage());
                }

            }
            
        }

        return $this->render('enfant/new.html.twig', [
            'enfant' => $enfant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/consultation/{id}", name="enfant_consultation", methods={"GET"})
     */
    public function show(Enfant $enfant): Response
    {
        $repEnfant = $this->getDoctrine()->getRepository(Enfant::class);

        $respLegaux = $enfant->getResponsableLegal();

        $corrAdmin = $enfant->getCorrespondantAdministratif();

        return $this->render('enfant/show.html.twig', [
            'enfant' => $enfant,
            'responsablesLegaux' => $respLegaux,
            'correspondantAdministratif' => $corrAdmin,
        ]);
    }

    /**
     * @Route("/modification/{id}", name="enfant_modification", methods={"GET","POST"})
     */
    public function edit(Request $request, Enfant $enfant, ValidatorInterface $validator): Response
    {
        $manager=$this->getDoctrine()->getManager();

        $form = $this->createForm(EnfantType::class, $enfant);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()){
                $donnes_enfant = $form->getData();
            //Récupération des données formulaires de saisie d'un éventuel nouvel établissement/correspondant administratif/responsable légal
                $donnees_newEtablissement = $donnes_enfant->getNewEtablissement();
                $donnees_newRespLegal = $donnes_enfant->getNewResponsableLegal();
                $donnees_newCorrespAdmin = $donnes_enfant->getNewCorrespondantAdministratif();

                if($donnees_newEtablissement != null){
                    $this->enregistrerNouvelEtablissement($donnees_newEtablissement, $enfant);
                }

            //Enregistrement de l'éventuel nouveau établissement
                if($donnees_newRespLegal != null){
                    $this->enregisterNouveauResp($donnees_newRespLegal, $enfant);
                }

            //Enregistrement de l'éventuel correspondant administratif
                if($donnees_newCorrespAdmin != null){
                    $this->enregistrerNouveauCorresp($donnees_newCorrespAdmin, $enfant);
                }

                $manager->flush();

                $this->addFlash('success', "La fiche de ".$donnes_enfant->getPrenom()." ".$donnes_enfant->getNom()." a été modifiée avec succès !");

                return $this->redirectToRoute('enfant_index');


            }else{
                $errors = $validator->validate($form->getData());

                foreach ($errors as $error) {
                    $this->addFlash('error', $error->getMessage());
                }
            }
        }

        return $this->render('enfant/edit.html.twig', [
            'enfant' => $enfant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/consultation/{id}", name="enfant_suppression", methods={"DELETE"})
     */
    public function delete(Request $request, Enfant $enfant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enfant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($enfant);
            $entityManager->flush();
        }

        $this->addFlash('success', $enfant->getPrenom()." ".$enfant->getNom().' a été désinscrit.');

        return $this->redirectToRoute('enfant_index');
    }




    private function enregistrerNouvelEtablissement(Etablissement $donnees_newEtablissement, Enfant $enfant){
        $new_etablissement = new Etablissement();
        $new_etablissement->setNom($donnees_newEtablissement->getNom());
        $new_etablissement->setVille($donnees_newEtablissement->getVille());

        $this->getDoctrine()->getManager()->persist($new_etablissement);
        $enfant->setEtablissement($new_etablissement);
    }

    private function enregisterNouveauResp(ResponsableLegal $donnees_newRespLegal, Enfant $enfant){
        $new_respLegal = new ResponsableLegal();

        $new_respLegal->setNom($donnees_newRespLegal->getNom());
        $new_respLegal->setPrenom($donnees_newRespLegal->getPrenom());
        $new_respLegal->setEmail($donnees_newRespLegal->getEmail());
        $new_respLegal->setTelDom($donnees_newRespLegal->getTelDom());
        $new_respLegal->setTelPort($donnees_newRespLegal->getTelPort());
        $new_respLegal->setTelTrav($donnees_newRespLegal->getTelTrav());

        $this->getDoctrine()->getManager()->persist($new_respLegal);
        $enfant->setResponsableLegal($new_respLegal);
    }

    private function enregistrerNouveauCorresp(CorrespondantAdministratif $donnees_newCorrespAdmin, Enfant $enfant){
        $new_correspAdmin = new CorrespondantAdministratif();

        $manager=$this->getDoctrine()->getManager();

        $responsable = $donnees_newCorrespAdmin->getNewResponsableLegal();

        if($responsable != null){//Si le formulaire a été rempli
            enregisterNouveauResp($responsable);
            $new_correspAdmin->setResponsableLegal($responsable);
        }else{
            $new_correspAdmin->setResponsableLegal($donnees_newCorrespAdmin->getResponsableLegal());
        }
        
        $new_correspAdmin->setNumSecu($donnees_newCorrespAdmin->getNumSecu());
        $new_correspAdmin->setAideCaf($donnees_newCorrespAdmin->getAideCaf());
        $new_correspAdmin->setAideMsa($donnees_newCorrespAdmin->getAideMsa());
        $new_correspAdmin->setAideAutres($donnees_newCorrespAdmin->getAideAutres());

        $manager->persist($new_correspAdmin);

        $enfant->setCorrespondantAdministratif($new_correspAdmin);
    }
}

templates/enfant/_delete_form.html.twig
<form method="post" action="{{ path('enfant_suppression', {'id': enfant.id}) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enfant.id) }}">
    <button class="btn btn-danger">Désinscrire</button>
</form>

templates/enfant/_form.html.twig
{{ form_start(form) }}
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Informations concernant l'enfant</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Responsables légaux</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Séjours</a>
</div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <div class="row">
        <div class="col-md-6">
            <div>
                {{ form_label(form.nom,"Nom",{'errors': false})}}
                {{ form_widget(form.nom) }}
            </div>
            <div>
                {{ form_label(form.prenom,"Prénom",{'errors': false})}}
                {{ form_widget(form.prenom) }}
            </div>
            <br>
            <div>
                {{ form_label(form.date_naiss,"Date de naissance",{'errors': false})}}
                {{ form_widget(form.date_naiss) }}
            </div>
            <div>
                {{ form_label(form.remarque,"Remarques",{'errors': false})}}
                {{ form_widget(form.remarque) }}
            </div>
        </div>
        <div class="col-md-6">
            <div>
                {{ form_label(form.adresse_1,"Adresse",{'errors': false})}}
                {{ form_widget(form.adresse_1) }}
            </div>
            <br>
            <div>                
                {{ form_label(form.adresse_2,"Complément d'adresse (falcultatif)",{'errors': false})}}
                {{ form_widget(form.adresse_2) }}
            </div>
            <div>                
                {{ form_label(form.ville,null,{'errors': false})}}
                {{ form_widget(form.ville) }}
            </div>
            <div>                
                {{ form_label(form.code_postal,null,{'errors': false})}}
                {{ form_widget(form.code_postal) }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div>
        {{ form_label(form.etablissement,"Établissement",{'errors': false})}}
        {{ form_widget(form.etablissement) }}
    </div>
    <div>
        <h5>Renseignez votre établissement ici s'il n'existe pas déjà</h5>
        <div>
            {{ form_label(form.new_etablissement.nom,null,{'errors': false})}}
            {{ form_widget(form.new_etablissement.nom) }}
        </div>
        <div>
            {{ form_label(form.new_etablissement.ville,"Ville",{'errors': false})}}
            {{ form_widget(form.new_etablissement.ville) }}
        </div>
    </div>
        </div>
        <div class="col-md-6">
            {{ form_row(form.centre) }}
        </div>
    </div>

</div>

<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
  <div class="row">
    <div class="col-md-6">
        {{ form_row(form.correspondant_administratif) }}
        <h5>Renseignez le correspondant administratif ici s'il n'existe pas déjà</h5>
        <div>
            {{ include('enfant/_form_newCorresp.html.twig') }}
        </div>
    </div>
    <div class="col-md-6">
        {{ form_label(form.responsable_legal,"Deuxième responsable légal (falcultatif)",{'errors': false}) }}
        {{ form_widget(form.responsable_legal) }}
        <br>
        <h5>Renseignez le responsable légal ici s'il n'existe pas déjà</h5>
        {{ include('enfant/_form_newResp.html.twig') }}
    </div>
</div>
</div>
<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
  <div>
    <center>
		{{ form_label(form.sejour,"Séjours",{'errors': false}) }}
		{{ form_widget(form.sejour) }}
    </center>
</div>
</div>
<br />
<button type="submit" class="btn btn-primary" id="vrai_submit" hidden>Enregistrer !</button>
</div>
{{ form_end(form) }}

templates/enfant/_form_newCorresp.html.twig
<div>
	{{ form_label(form.new_correspondantAdministratif.responsable_legal,null,{'errors': false})}}
	{{ form_widget(form.new_correspondantAdministratif.responsable_legal)}}
</div>
<div>
	<h6>Un nouveau responsable ? Enregistrez-le !</h6>
	<div>
		{{ form_label(form.new_correspondantAdministratif.new_responsableLegal.nom,"Nom",{'errors': false})}}
		{{ form_widget(form.new_correspondantAdministratif.new_responsableLegal.nom) }}
	</div>
	<div>
		{{ form_label(form.new_correspondantAdministratif.new_responsableLegal.prenom,"Prénom",{'errors': false})}}
		{{ form_widget(form.new_correspondantAdministratif.new_responsableLegal.prenom) }}
	</div>
	<div>
		{{ form_label(form.new_correspondantAdministratif.new_responsableLegal.email,"Email",{'errors': false})}}
		{{ form_widget(form.new_correspondantAdministratif.new_responsableLegal.email) }}
	</div>
	<div>
		{{ form_label(form.new_correspondantAdministratif.new_responsableLegal.tel_dom,"Téléphone (domicile)",{'errors': false})}}
		{{ form_widget(form.new_correspondantAdministratif.new_responsableLegal.tel_dom) }}
	</div>
	<div>
		{{ form_label(form.new_correspondantAdministratif.new_responsableLegal.tel_port,"Téléphone (portable)",{'errors': false})}}
		{{ form_widget(form.new_correspondantAdministratif.new_responsableLegal.tel_port) }}
	</div>
	<div>
		{{ form_label(form.new_correspondantAdministratif.new_responsableLegal.tel_trav,"Téléphone (professionnel)",{'errors': false})}}
		{{ form_widget(form.new_correspondantAdministratif.new_responsableLegal.tel_trav) }}
	</div>
</div>
<br>
<br>
<div>
	{{ form_label(form.new_correspondantAdministratif.num_secu, "Numéro sécurité sociale",{'errors': false})}}
	{{ form_widget(form.new_correspondantAdministratif.num_secu)}}
</div>
<div>
	{{ form_label(form.new_correspondantAdministratif.aide_caf, "Aide CAF",{'errors': false})}}
	{{ form_widget(form.new_correspondantAdministratif.aide_caf)}}
</div>
<div>
	{{ form_label(form.new_correspondantAdministratif.aide_msa, "Aide MSA",{'errors': false})}}
	{{ form_widget(form.new_correspondantAdministratif.aide_msa)}}
</div>
<div>
	{{ form_label(form.new_correspondantAdministratif.aide_autres, "Autres aides",{'errors': false})}}
	{{ form_widget(form.new_correspondantAdministratif.aide_autres)}}
</div>

templates/enfant/_form_newResp.html.twig
<div>
    {{ form_label(form.new_responsableLegal.nom,"Nom",{'errors': false})}}
    {{ form_widget(form.new_responsableLegal.nom) }}
</div>
<div>
    {{ form_label(form.new_responsableLegal.prenom,"Prénom",{'errors': false})}}
    {{ form_widget(form.new_responsableLegal.prenom) }}
</div>
<div>
    {{ form_label(form.new_responsableLegal.email,"Email",{'errors': false})}}
    {{ form_widget(form.new_responsableLegal.email) }}
</div>
<div>
    {{ form_label(form.new_responsableLegal.tel_dom,"Téléphone (domicile)",{'errors': false})}}
    {{ form_widget(form.new_responsableLegal.tel_dom) }}
</div>
<div>
    {{ form_label(form.new_responsableLegal.tel_port,"Téléphone (portable)",{'errors': false})}}
    {{ form_widget(form.new_responsableLegal.tel_port) }}
</div>
<div>
    {{ form_label(form.new_responsableLegal.tel_trav,"Téléphone (professionnel)",{'errors': false})}}
    {{ form_widget(form.new_responsableLegal.tel_trav) }}
</div>

templates/enfant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enfant{% endblock %}

{% block titrePage %}Consultation de la fiche d'un enfant{% endblock %}

{% block outils %}
<a type="button" href="{{path('enfant_creation')}}" class="btn btn-success">
    Inscrire un nouvel enfant
</a>
    <a type="button" href="{{path('enfant_modification',{'id':enfant.id})}}" class="btn btn-primary">
         Modifier
     </a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalSuppressionEnfant">
            Désinscrire
     </button>
    <a type="button" href="{{path('enfant_index')}}" class="btn btn-primary">
        Retour
    </a>
     
{% endblock %}

{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ enfant.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ enfant.prenom }}</td>
            </tr>
            <tr>
                <th>Date de naissance</th>
                <td>{{ enfant.dateNaiss ? enfant.dateNaiss|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Établissement scolaire</th>
                <td>{{ enfant.etablissement ? enfant.etablissement.nom : 'Aucun' }}</td>
            </tr>
            <tr>
                <th>Centre</th>
                <td>{{ enfant.centre.ville }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ enfant.adresse1 }}</td>
            </tr>
            <tr>
                <th>Complément d'adresse</th>
                <td>{{ enfant.adresse2 }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ enfant.ville }}</td>
            </tr>
            <tr>
                <th>Code Postal</th>
                <td>{{ enfant.codePostal }}</td>
            </tr>            
            <tr>
                <th>Remarques</th>
                <td>{{ enfant.remarque }}</td>
            </tr>
            <tr>
                <th>Correspondant administratif</th>
                <td>
                     {{ enfant.correspondantAdministratif.responsableLegal.nom|upper }} {{ enfant.correspondantAdministratif.responsableLegal.prenom}}
                </td>
            </tr>
            <tr>
                <th>Deuxième responsable légal</th>
                <td>
                    {% if enfant.responsableLegal is not null %} 
                        {{enfant.responsableLegal.nom|upper}} {{enfant.responsableLegal.prenom}}
                    {% endif %} 
                </td>
            </tr>
            {% if enfant.sejour is not null %}
            <tr>
                <th>Séjours</th>
                <td>{% for sejour in enfant.sejour %}
                        {{ sejour }} </br>
                    {% endfor %}
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <!-- Modal suppression enfant -->
<div class="modal fade" id="modalSuppressionEnfant" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Désinscrire un enfant</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
  </div>
  <div class="modal-body">
    <h3><center>Êtes-vous sûr de vouloir désinscrire {{enfant.prenom}} {{enfant.nom}} ?</center></h3>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ne pas désinscrire</button>{{ include('enfant/_delete_form.html.twig') }}
    </div>
</div>
{% endblock %}