src/Entity/Affaire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AffaireRepository")
 * @UniqueEntity(fields={"nom_francais"}, message="Cette affaire existe déjà !")
 */
class Affaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     * @Assert\NotBlank
     * @Assert\Regex(pattern="/[0-9]+/i",
     *              match=false,
     *              message = "On ne peut pas créer une affaire avec des chiffres !")
     */
    private $nom_francais;

    /**
     * @ORM\Column(type="string", length=40)
     * @Assert\NotBlank
     * @Assert\Regex(pattern="/[0-9]+/i",
     *              match=false,
     *              message = "On ne peut pas créer une affaire avec des chiffres !")
     */
    private $nom_basque;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ListeAffaire", inversedBy="affaire")
     */
    private $listeAffaires;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeAffaire", inversedBy="affaires")
     */
    private $type_affaire;

    public function __construct()
    {
        $this->listeAffaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFrancais(): ?string
    {
        return $this->nom_francais;
    }

    public function setNomFrancais(string $nom_francais): self
    {
        $this->nom_francais = $nom_francais;

        return $this;
    }

    public function getNomBasque(): ?string
    {
        return $this->nom_basque;
    }

    public function setNomBasque(string $nom_basque): self
    {
        $this->nom_basque = $nom_basque;

        return $this;
    }

    public function getTypeAffaire(): ?TypeAffaire
    {
        return $this->type_affaire;
    }

    public function setTypeAffaire(?TypeAffaire $type_affaire): self
    {
        $this->type_affaire = $type_affaire;

        return $this;
    }

    /**
     * @return Collection|ListeAffaire[]
     */
    public function getListeAffaire(): Collection
    {
        return $this->listeAffaires;
    }

    public function addListeAffaire(ListeAffaire $listeAffaire): self
    {
        if (!$this->listeAffaires->contains($listeAffaire)) {
            $this->listeAffaires[] = $listeAffaire;
        }

        return $this;
    }

    public function removeListeAffaire(ListeAffaire $listeAffaire): self
    {
        if ($this->listeAffaires->contains($listeAffaire)) {
            $this->listeAffaires->removeElement($listeAffaire);
        }

        return $this;
    }
}

src/Entity/Sejour.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SejourRepository")
 */
class Sejour
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $num_ministre;

    /**
     * @ORM\Column(type="integer")
	 * 
     */
    private $cout;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ListeAffaire", inversedBy="sejour")
     */
    private $listeAffaire;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Enfant", mappedBy="sejour", cascade={"persist"})
     */
    private $enfants;

    public function __construct()
    {
        $this->enfants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNumMinistre(): ?string
    {
        return $this->num_ministre;
    }

    public function setNumMinistre(string $num_ministre): self
    {
        $this->num_ministre = $num_ministre;

        return $this;
    }

    public function getCout(): ?int
    {
        return $this->cout;
    }

    public function setCout(int $cout): self
    {
        $this->cout = $cout;

        return $this;
    }

    public function getListeAffaire(): ?ListeAffaire
    {
        return $this->listeAffaire;
    }

    public function setListeAffaire(?ListeAffaire $listeAffaire): self
    {
        $this->listeAffaire = $listeAffaire;

        return $this;
    }

    /**
     * @return Collection|Enfant[]
     */
    public function getEnfants(): Collection
    {
        return $this->enfants;
    }

    public function addEnfant(Enfant $enfant): self
    {
        if (!$this->enfants->contains($enfant)) {
            $this->enfants[] = $enfant;
            $enfant->addSejour($this);
        }

        return $this;
    }

    public function removeEnfant(Enfant $enfant): self
    {
        if ($this->enfants->contains($enfant)) {
            $this->enfants->removeElement($enfant);
            $enfant->removeSejour($this);
        }

        return $this;
    }

    public function __toString(){
        return $this->getNom()." (du ".$this->getDateDebut()->format("d/m/Y")." au ".$this->getDateFin()->format("d/m/Y").")";
    }
}

src/Form/SejourType.php
<?php

namespace App\Form;

use App\Entity\Sejour;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

use Doctrine\ORM\EntityRepository;

use App\Entity\Enfant;
use App\Entity\Affaire;
use App\Entity\ListeAffaire;

use App\Form\ListeAffaireType;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class SejourType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('date_debut', DateType::class, [
                'empty_data' => ['year' => 'Année', 'month' => 'Mois', 'day' => 'Jour'],
                'years'=> range(date('Y'), date('Y')+10),
                'format' => 'dd MM yyyy'])
            ->add('date_fin', DateType::class, [
                'empty_data' => ['year' => 'Année', 'month' => 'Mois', 'day' => 'Jour'],
                'years'=> range(date('Y'), date('Y')+10),
                'format' => 'dd MM yyyy'])
            ->add('num_ministre')
            ->add('cout')
            ->add('listeAffaire', EntityType::class, ['class'=>ListeAffaire::class,
													  'choice_label' => 'nom_francais',
                                                      'expanded'=>false,
                                                      'multiple'=>false, ]) 
			->add('enfants', EntityType::class, ['class'=>Enfant::class,
												  'choice_label' => function($enfants)
												  { 
													  return $enfants -> getNom()." ".$enfants -> getPrenom();
												  },
												  'query_builder' => function (EntityRepository $entityRepo ) 
													{
														return $entityRepo->createQueryBuilder('e')
																->orderBy('e.nom', 'ASC');
													},
												  'expanded'=>true,
												  'multiple'=>true,])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sejour::class,
        ]);
    }

}

src/Controller/SejourController.php
<?php

namespace App\Controller;

use App\Entity\Sejour;
use App\Form\SejourType;
use App\Repository\SejourRepository;

use App\Entity\Enfant;
use App\Form\EnfantType;
use App\Repository\EnfantRepository;

use App\Entity\ListeAffaire;
use App\Form\ListeAffaireType;
use App\Repository\ListeAffaireRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
* @Route("/gestionSejours")
*/
class SejourController extends AbstractController
{
  /**
  * @Route("/", name="sejour_index", methods={"GET"})
  */
  public function index(SejourRepository $sejourRepository): Response
  {
    return $this->render('sejour/index.html.twig', [
      'sejours' => $sejourRepository->findAll(),
    ]);
  }

  /**
  * @Route("/creation", name="sejour_creation", methods={"GET","POST"})
  */
  public function new(Request $request, ListeAffaireRepository $listeAffaireRepository, EnfantRepository $enfantRepository): Response
  {
    $sejour = new Sejour();
    $form = $this->createForm(SejourType::class, $sejour);
    $form->handleRequest($request);
	
	$listeEnfant = $enfantRepository -> findAll();

    if ($form->isSubmitted() && $form->isValid()) 
	{
		$donnees_sejour = $form->getData();

	  foreach($listeEnfant as $enfant)
	  {
		if($donnees_sejour -> getEnfants() -> contains($enfant) )
		{
			$enfant -> addSejour($sejour);
		}
		else
		{
			$enfant -> removeSejour($sejour);
		}
	  }
		
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($sejour);
      $entityManager->flush();

      return $this->redirectToRoute('sejour_index');
    }

    return $this->render('sejour/new.html.twig', [
      'sejour' => $sejour,
      'listeAffaire' => $listeAffaireRepository -> findAll(),
      'form' => $form->createView(),
    ]);
  }

  /**
  * @Route("/consultation/{id}", name="sejour_consultation", methods={"GET"})
  */
  public function show(Sejour $sejour): Response
  {
    return $this->render('sejour/show.html.twig', [
      'sejour' => $sejour,
    ]);
  }

  // DEBUT
  /**
  * @Route("/modification/{id}", name="sejour_modification", methods={"GET","POST"})
  */
  public function edit(Request $request, Sejour $sejour, ListeAffaireRepository $listeAffaireRepository, EnfantRepository $enfantRepository): Response
  {
	$form = $this->createForm(SejourType::class, $sejour);
	$form->handleRequest($request);

	$listeEnfant = $enfantRepository -> findAll();
	/*dump( $listeAffaireRepository -> findAll() );
	exit();*/
	if ($form->isSubmitted() && $form->isValid() )
	{
	  $donnees_sejour = $form->getData();

	  foreach($listeEnfant as $enfant)
	  {
		if($donnees_sejour -> getEnfants() -> contains($enfant) )
		{
			$enfant -> addSejour($sejour);
		}
		else
		{
			$enfant -> removeSejour($sejour);
		}
	  }

	$this->getDoctrine()->getManager()->persist($donnees_sejour);
	$this->getDoctrine()->getManager()->flush();

	$this->addFlash('success', "Le séjour ".$donnees_sejour->getNom()." a été modifié avec succès !");

	return $this->redirectToRoute('sejour_index');
	}

	return $this->render('sejour/edit.html.twig', [
	'sejour' => $sejour,
	'listeAffaire' => $listeAffaireRepository -> findAll(),
	'form' => $form->createView(),
	]);
}


/**
* @Route("/consultation/{id}", name="sejour_suppression", methods={"DELETE"})
*/
public function delete(Request $request, Sejour $sejour): Response
{
  if ($this->isCsrfTokenValid('delete'.$sejour->getId(), $request->request->get('_token'))) {
    $entityManager = $this->getDoctrine()->getManager();
    $entityManager->remove($sejour);
    $entityManager->flush();
  }

  return $this->redirectToRoute('sejour_index');
}
}

templates/sejour/_delete_form.html.twig
<form method="post" action="{{ path('sejour_suppression', {'id': sejour.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce séjour ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sejour.id) }}">
    <button class="btn btn-danger"> Supprimer </button>
</form>

templates/sejour/_form.html.twig
{{ form_start(form) }}

<button type="submit" class="btn btn-primary"> Valider </button>

<div class="modal-body row">
	<div class="col-md-6">
		
		{# Partie concernant le séjour #}
		<fieldset>
			<div>
				{{ form_label(form.nom,"Nom",{'errors': false})}}
				{{ form_widget(form.nom) }}
			</div>
			
			<div class="container">
				<div class="row">
					<div class="col">
						{{ form_label(form.date_debut,"Date de début",{'errors': false})}}
						{{ form_widget(form.date_debut) }}
					</div>
					<div class="col">
						{{ form_label(form.date_fin,"Date de fin",{'errors': false})}}
						{{ form_widget(form.date_fin) }}
					</div>
					<div class="w-100"></div>
					<div class="col">
						{{ form_label(form.num_ministre,"N° Ministère",{'errors': false})}}
						{{ form_widget(form.num_ministre) }}
					</div>
					<div class="col">
						{{ form_label(form.cout,"Coût",{'errors': false})}}
						{{ form_widget(form.cout) }}
					</div>
				</div>
			</div>	
		</fieldset>
		
	</br></br>

	<div>
		{{ form_label(form.listeAffaire,"Liste d'affaires pour ce séjour", {'errors': false}) }}
		{{ form_widget(form.listeAffaire, {'attr': {'onChange': 'displayAffaire()' }}) }}
	</div>	
	
	<script>	
		// Il faut créer un tableau JS à partir du tableau php
		var lAffaireJS = new Object();
		theTableau = Array();
			
		lAffaireJS.leTableau = theTableau;
		
		{% for liste in listeAffaire %}
			objetListe = new Object();
			objetListe.nomfrancais = "{{ liste.nomFrancais }}";
			objetListe.nombasque = "{{ liste.nomBasque }}";
			
			theaffaire = Array();
			objetListe.affaire = theaffaire;
			
			// Ici, on a un objet objetListe avec pour attribut nomfrancais, 
			// nombasque et un tableau d'affaire
			
			{% for a in liste.affaire %}
				objetAffaire = new Object();
				objetAffaire.affaireFR = "{{ a.nomFrancais }}";
				objetAffaire.affaireBA = "{{ a.nomBasque }}";
				objetAffaire.affaireTY = "{{ a.typeAffaire.nom }}";
				objetListe.affaire.push( objetAffaire );
			{% endfor %}
			
			// Ici, on a un objet objetAffaire avec pour attribut nomFrancais,
			// nomBasque et son type d'affaire
			
			// On ajoute l'objet au tableau		
			lAffaireJS.leTableau.push( objetListe );
			
		{% endfor %}
		
		console.log( theTableau );
		console.log( lAffaireJS );
	
		function displayAffaire()
		{
			var listeChoisie = document.getElementById("sejour_listeAffaire");
			var body = document.getElementById("tabAffaires");
		
			var index = listeChoisie.selectedIndex;
				
			body.innerHTML = "";
			
			for(var i = 0; i <= theTableau[index].affaire.length-1; i++)
			{			
				body.innerHTML +=
					"<tr>" +
						"<td> 1 </td>" +
						"<td>" + theTableau[index].affaire[i].affaireFR + "</td>" +
						"<td>" + theTableau[index].affaire[i].affaireBA + "</td>" +
						"<td>" + theTableau[index].affaire[i].affaireTY + "</td>" +
					"</tr>";
			}	
		}
	</script>
	
	<table class="table">
		<thead>
			<tr>
				<th> Quantité </th>
				<th> Français </th>
				<th> Euskara </th>
				<th> Type </th>
			</tr>
		</thead>
		<tbody id="tabAffaires">
			{% if sejour.listeAffaire is not null %}
				{% for affaire in sejour.listeAffaire.affaire  %}
					<tr id = "tr">
						<td> 1 </td>
						<td> {{ affaire.nomFrancais }} </td>
						<td> {{ affaire.nomBasque}} </td>
						<td> {{ affaire.typeAffaire.nom }} </td>
					</tr>
				{% endfor %}
			{% endif %}
		</tbody>
	</table>
	
</div>
<div class="col-md-6">

	{# Partie concernant les enfants #}

	Liste des enfants inscrits à ce séjour :
	{#
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAjoutEnfants">
          Modifier
	</button>
	#}
	
		{{ form_widget(form.enfants) }}
	
	</div>
</div>
{{ form_end(form) }}

{#
	Le pop-up
	<div class="modal fade bd-example-modal-xl" id="modalAjoutEnfants" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-xl" role="document">
			<div class="modal-content">
			
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLongTitle"> Modification de la liste des enfants </h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
					</button>
				</div>
			
					
			<div class="modal-body row">	
				<div class="col-md-5">
					Enfants inscrits au centre
					
					<table class="table">
						<thead>
							<tr>
								<th> Nom </th>
								<th> Prénom </th>
								<th> Centre </th>
							</tr>
						</thead>
						<tbody>
							{% if sejour.enfants is not null %}
							{% for enfant in sejour.enfants  %}
							<tr>
								<td> {{enfant.nom}} </td>
								<td> {{enfant.prenom}} </td>
								<td> {{enfant.centre.ville}} </td>
							</tr>
							{% endfor %}
							{% endif %}
						</tbody>
					</table>
				</div>
				
				<div class="col-md-2">
					</br>
					</br>
				
					<div class="text-center">
					
						Ajouter à la liste

						<button class="btn btn-primary"> >>> </button>	
						
					</div>		
					
					</br>
					
					<div class="text-center">
						Retirer de la liste

						<button class="btn btn-primary"> <<< </button>

					</div>
					
					</br>
					</br>
					</br>
					
					<div class="text-center">
						<button class="btn btn-primary"> Vider la liste </button>
					</div>				
				</div>
				
				
				<div class="col-md-5">
					Enfants inscrits à ce séjour
					<table class="table">
						<thead>
							<tr>
								<th> Nom </th>
								<th> Prénom </th>
								<th> Centre </th>
							</tr>
						</thead>
						<tbody>
							{% if sejour.enfants is not null %}
							{% for enfant in sejour.enfants  %}
							<tr>
								<td> {{enfant.nom}} </td>
								<td> {{enfant.prenom}} </td>
								<td> {{enfant.centre.ville}} </td>
							</tr>
							{% endfor %}
							{% endif %}
						</tbody>
					</table>
				</div>
			</div>
				
			
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal"> Annuler </button> 
				<button type="button" class="btn btn-primary" data-dismiss="modal"> Enregistrer </button> 
			</div>
			
		</div>
	</div>
#}

templates/sejour/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des séjours {% endblock %}

{% block titrePage %}Gestion des séjours{% endblock %}

{% block outils %}
<a class="btn btn-success" href="{{ path('sejour_creation') }}" role="button"> Créer un nouveau séjour </a>
{% endblock %}

{% block body %}


    <table class="table">
        <thead>
            <tr>
                <th>Séjour</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for sejour in sejours %}
            <tr>
                <td>{{ sejour.nom }}</td>
                <td>{{ sejour.dateDebut ? sejour.dateDebut|date('d/m/Y') : '' }}</td>
                <td>{{ sejour.dateFin ? sejour.dateFin|date('d/m/Y') : '' }}</td>
                <td>
                    <a class="btn btn-secondary" href="{{ path('sejour_consultation', {'id': sejour.id}) }}"> Consulter </a>
                    <a class="btn btn-secondary" href="{{ path('sejour_modification', {'id': sejour.id}) }}"> Modifier </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun séjour n'a été eregistré... Pourquoi ne pas en créer un maintenant ?</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   {# <a href="{{ path('sejour_creation') }}">Create new</a> #}
{% endblock %}

templates/sejour/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Consultation d'un séjour {% endblock %}

{% block titrePage %}Consultation du séjour : {{sejour.nom}}{% endblock %}

{% block outils %}<a class="btn btn-success" href="{{ path('sejour_creation') }}" role="button"> Créer </a>
<a class="btn btn-primary" href="#" role="button"> Ouvrir </a>

<div class="btn-group" role="group">
  <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Options
  </button>
  <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    <a class="dropdown-item" href="{{ path('sejour_modification', {'id': sejour.id}) }}"> Modifier </a>
    {{ include('sejour/_delete_form.html.twig') }}
    <a class="dropdown-item" href="#"> Imprimer, générer </br> et publipostage </a>
  </div>
</div>

<a class="btn btn-primary disabled" href="#" role="button"> Valider </a>
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalSuppressionSejour">
	Supprimer
</button>
<a class="btn btn-primary" href="{{ path('sejour_index') }}" role="button"> Retour </a>  {% endblock %}


{% block body %}
	<hr>

	<div class="modal-body row">
	  <div class="col-md-6">

		{# Partie concernant le séjour #}
			<fieldset disabled>
				<div class="container">
					<div class="row">
						<div class="col-sm-2"> Séjour </div>
						<div class="col-sm-10"> <input type="text" placeholder=" {{sejour.nom}} "> </div>

						<div class="w-100"></div>

						<div class="col"> Date de début </div>
						<div class="col"> <input type= text placeholder=" {{ sejour.dateDebut ? sejour.dateDebut|date('d/m/Y') : '' }} "> </div>
						<div class="col"> Date de fin </div>
						<div class="col"> <input type= text placeholder=" {{ sejour.dateFin ? sejour.dateFin|date('d/m/Y') : '' }} "> </div>

						<div class="w-100"></div>

						<div class="col"> N° Ministère </div>
						<div class="col"> <input type= text placeholder=" {{sejour.numMinistre}} "> </div>
						<div class="col"> Coût </div>
						<div class="col"> <input type= text placeholder=" {{sejour.cout}} "> </div>
					</div>
				</div>
			</fieldset>

			</br></br>

			
			Liste d'affaires pour ce séjour : 
			<select class=form-control-5 disabled>
					<option value=un> {{sejour.listeAffaire.nomFrancais }} </option>
			</select>
			<a class="btn btn-primary disabled" href="#" role="button"> Modifier </a>

			<table class="table">
				<thead>
					<tr>
						<th> Quantité </th>
						<th> Français </th>
						<th> Euskara </th>
						<th> Type </th>
					</tr>
				</thead>
				<tbody>
					{% for affaire in sejour.listeAffaire.affaire  %}
						<tr>
							<td> 1 </td>
							<td> {{ affaire.nomFrancais }} </td>
							<td> {{ affaire.nombasque }} </td>
							<td> {{ affaire.typeAffaire.nom }} </td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

	</div>
	<div class="col-md-6">

		{# Partie concernant les enfants #}
			Liste des enfants inscrits à ce séjour
			<table class="table">
				<thead>
					<tr>
						<th> Nom </th>
						<th> Prénom </th>
						<th> Centre </th>
					</tr>
				</thead>
				<tbody>
					{% for enfant in sejour.enfants  %}
						<tr>
							<td> {{ enfant.nom }} </td>
							<td> {{ enfant.prenom }} </td>
							<td> {{ enfant.centre.ville }} </td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

	  </div>
	</div>

    {#
	<table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sejour.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ sejour.nom }}</td>
            </tr>
            <tr>
                <th>Date début</th>
                <td>{{ sejour.dateDebut ? sejour.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date fin</th>
                <td>{{ sejour.dateFin ? sejour.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>N° ministère</th>
                <td>{{ sejour.numMinistre }}</td>
            </tr>
            <tr>
                <th>Coût</th>
                <td>{{ sejour.cout }}</td>
            </tr>
        </tbody>
    </table>
	#}

    {#<a class="btn btn-primary" href="{{ path('sejour_index') }}"> Retour</a>
	<a class="btn btn-primary" href="{{ path('sejour_modification', {'id': sejour.id}) }}"> Modifier </a> #}

	<div class="modal fade" id="modalSuppressionSejour" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLongTitle"> /!\ Suppression d'un séjour </h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
					</button>
				</div>
			<div class="modal-body">
			<h3><center>Êtes-vous sûr de vouloir supprimer le séjour {{sejour.nom}} ?</center></h3>
		</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Ne pas supprimer</button>{{ include('sejour/_delete_form.html.twig') }}
			</div>
		</div>
	</div>

{% endblock %}